/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdaserver;

import java.io.IOException;
import java.net.ServerSocket;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.microsoft.sqlserver.jdbc.SQLServerDriver;
import java.awt.Color;

/**
 *
 * @author Tiago Ventura
 */
public class Visor extends javax.swing.JFrame {

    //-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    /*
                                                                          ┌────────────────────┐
                                                                          │             DEFINIÇÃO             │
                                                                          │                DE                 │   
                                                                          │             VARIAVEIS             │
                                                                          └────────────────────┘                                                                                   
                                                                                                                                                                                                    */
    
    public static Connection con;  
    ArrayList<Waiting> waiters = new ArrayList<>();
    Thread t;
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
    public Visor() {
        this.t = new Thread(new Runnable() {
            @Override
            public void run() {
                ServerSocket listener = null;
                try {
                    listener = new ServerSocket(100);
                } catch (IOException ex) {
                    Logger.getLogger(Visor.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    while (true) {
                        Waiting temp54 = new Waiting(listener.accept());
                        temp54.start();
                        waiters.add(temp54);
                        
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex) {
                            ex.printStackTrace();
                        }
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Visor.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        listener.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Visor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://MEANMACHINE;databaseName=viptronica", "sa", "Vip%2015");
        
            
                        } catch (SQLException ex) {
            Logger.getLogger(Visor.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents(); 
        this.getContentPane().setBackground(new Color(250,250,250));
        t.start();
    }
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server PDA");
        setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 76)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Servidor PDA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdaserver/logo_vip_clear.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
